version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: khalander_mongo_container
    ports:
      - "27017:27017"
    volumes:
      - khalander_mongo_data:/data/db
    networks:
      - khalander-network
    env_file:
      - .env

  backend:
    build:
      context: ./SERVER
      dockerfile: Dockerfile
      target: prod
    container_name: khalander_backend_container
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ./backend:/app
    networks:
      - khalander-network
    env_file:
      - .env
    depends_on:
      - db

  frontend-client:
    build:
      context: ./CLIENT
      dockerfile: Dockerfile
      target: prod
    container_name: khalander_client_container
    ports:
      - "${CLIENT_PORT}:80"
    volumes:
      - ./frontend:/app
    networks:
      - khalander-network
    env_file:
      - .env
    depends_on:
      - backend

  frontend-admin:
    build:
      context: ./ADMIN
      dockerfile: Dockerfile
      target: prod
    container_name: khalander_admin_container
    ports:
      - "${ADMIN_PORT}:80"
    volumes:
      - ./frontend:/app
    networks:
      - khalander-network
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  khalander_mongo_data:
  khalander_backend_data:
  khalander_client_data:
  khalander_admin_data:

networks:
  khalander-network:
    driver: bridge










































# version: "3.8"

# services:
#   db:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodata:/data/db

#   backend-dev:
#     build:
#       context: .
#       dockerfile: SERVER/Dockerfile
#       target: dev
#     volumes:
#       - ./backend:/app
#     ports:
#       - "4000:4000"
#     # environment:
#     #   - NODE_ENV=development
#     #   - MONGO_URI=mongodb://db:27017/mongodb
#     environment:
#       - MONGODB_URI='mongodb+srv://mini-project:mini-project@mlcluster.zkommql.mongodb.net/?retryWrites=true&w=majority&appName=MLcluster'
#       - PORT='8000'
#       - JWT_Secret_Key='Mohamm34566ed@#$%^&Khal89109437ander%*&^#Never%$^&Ever^&TRY_)ToGuess'
#       - NODE_ENV='development'
#       - FRONT_END_URL='http://localhost:5173'
#       - FRONT_END_URL_ADMIN='http://localhost:5174'
#       - CLOUDINARY_CLOUD_NAME='dsk16aew0'
#       - CLOUDINARY_API_KEY='414374266569697'
#       - CLOUDINARY_API_SECRET='f8yNLOdoE4CLM1HWk97CGVOJ01I'
#       - ADMIN_EMAIL='admin@weNours.dev.in'
#       - ADMIN_PASSWORD='ADMIN_PASSWORD'
#       - SMTP_USER='8a038b001@smtp-brevo.com'
#       - SMTP_PASSWORD='2GjUdtSJNX0L91pT'
#       - SMTP_PORT=587
#       - SENDER_EMAIL_SMT='khalandermohammed734@gmail.com'
#       - SMTP_HOST='smtp-relay.brevo.com'
#       - RAZORPAY_KEY_ID = ' '
#       - RAZORPAY_KEY_SECRET = ' '

#     depends_on:
#       - db

#   backend-prod:
#     build:
#       context: .
#       dockerfile: SERVER/Dockerfile
#       target: prod
#     ports:
#       - "8080:8080" 
#     # environment:
#     #   - NODE_ENV=production
#     #   - MONGO_URI=mongodb://db:27017/mongodb_prod
#     environment:
#       - MONGODB_URI='mongodb+srv://mini-project:mini-project@mlcluster.zkommql.mongodb.net/?retryWrites=true&w=majority&appName=MLcluster'
#       - PORT='8000'
#       - JWT_Secret_Key='Mohamm34566ed@#$%^&Khal89109437ander%*&^#Never%$^&Ever^&TRY_)ToGuess'
#       - NODE_ENV='production'
#       - FRONT_END_URL='http://localhost:5173'
#       - FRONT_END_URL_ADMIN='http://localhost:5174'
#       - CLOUDINARY_CLOUD_NAME='dsk16aew0'
#       - CLOUDINARY_API_KEY='414374266569697'
#       - CLOUDINARY_API_SECRET='f8yNLOdoE4CLM1HWk97CGVOJ01I'
#       - ADMIN_EMAIL='admin@weNours.dev.in'
#       - ADMIN_PASSWORD='ADMIN_PASSWORD'
#       - SMTP_USER='8a038b001@smtp-brevo.com'
#       - SMTP_PASSWORD='2GjUdtSJNX0L91pT'
#       - SMTP_PORT=587
#       - SENDER_EMAIL_SMT='khalandermohammed734@gmail.com'
#       - SMTP_HOST='smtp-relay.brevo.com'
#       - RAZORPAY_KEY_ID = ' '
#       - RAZORPAY_KEY_SECRET = ' '

#     depends_on:
#       - db

#   frontend-client-dev:
#     build:
#       context: .
#       dockerfile: CLIENT/Dockerfile
#       target: dev
#     volumes:
#       - ./frontend:/app
#     ports:
#       - "3000:3000"
#     # environment:
#     #   - NODE_ENV=development
#     #   - REACT_APP_API_URL=http://localhost:4000
#     environment:
#       - VITE_BACKEND_URL = 'http://localhost:8000'
#       - VITE_RAZORPAY_KEY_ID = ' '
#     depends_on:
#       - backend-dev

#   frontend-client-prod:
#     build:
#       context: .
#       dockerfile: frontend/Dockerfile
#       target: prod
#     ports:
#       - "8000:80"   # nginx inside container serves on port 80
#     # environment:
#     #   - NODE_ENV=production
#     #   - REACT_APP_API_URL=http://backend-prod:8080
#     environment:
#       - VITE_BACKEND_URL = 'http://localhost:8000'
#       - VITE_RAZORPAY_KEY_ID = ' '
#     depends_on:
#       - backend-prod

#   frontend-admin-dev:
#     build:
#       context: .
#       dockerfile: ADMIN/Dockerfile
#       target: dev
#     volumes:
#       - ./frontend:/app
#     ports:
#       - "3000:3000"
#     # environment:
#     #   - NODE_ENV=development
#     #   - REACT_APP_API_URL=http://localhost:4000
#     environment:
#       - VITE_BACKEND_URL='http://localhost:8000'
#     depends_on:
#       - backend-dev

#   frontend-admin-prod:
#     build:
#       context: .
#       dockerfile: ADMIN/Dockerfile
#       target: prod
#     ports:
#       - "8000:80"   # nginx inside container serves on port 80
#     # environment:
#     #   - NODE_ENV=production
#     #   - REACT_APP_API_URL=http://backend-prod:8080
#     environment:
#       - VITE_BACKEND_URL='http://localhost:8000'
#     depends_on:
#       - backend-prod

# volumes:
#   mongodata: